definitions:
  dto.LoginDTO:
    properties:
      password:
        description: 密码
        example: "123456"
        type: string
      username:
        description: 用户名
        example: root
        type: string
    type: object
  model.User:
    properties:
      account:
        description: 账号
        type: string
      age:
        description: 年龄
        type: integer
      createTime:
        description: 创建时间
        type: string
      email:
        description: 邮箱
        type: string
      gender:
        description: 性别
        type: integer
      id:
        description: id
        type: string
      name:
        description: 昵称
        type: string
      phone:
        description: 电话
        type: string
      picture:
        description: 头像
        type: string
      status:
        description: 是否启用
        type: boolean
      updateTime:
        description: 更新时间
        type: string
    type: object
  resp.Response:
    properties:
      code:
        description: 业务状态码
        example: 200
        type: integer
      data:
        description: 响应数据
      msg:
        description: 附加消息
        example: success
        type: string
    type: object
info:
  contact: {}
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: 输入账号密码登录，登陆成功返回登录token
      parameters:
      - description: 登录参数l
        in: body
        name: args
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 用户登录
      tags:
      - 用户
  /api/user/info:
    get:
      consumes:
      - application/json
      description: 获取当前登录用户的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/model.User'
                msg:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/resp.Response'
            - properties:
                code:
                  type: integer
                data:
                  type: object
                msg:
                  type: string
              type: object
      security:
      - Jwt: []
      summary: 用户信息
      tags:
      - 用户
securityDefinitions:
  Jwt:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
