server-name: im
host: localhost
port: 8080
#database: host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
database: root:123456@tcp(192.168.19.128:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
logger:
  level: debug
  filename: system
  path:
  maxsize: 10
  maxage: 30
  maxbackups: 30
Auth:
  #  jwt 安全码
  AccessSecret: asdasceqw
  #  jwt 过期时间
  AccessExpire: 3600